/**
 * Characterization test — pins the FULL buildTraceSpans output for one real
 * research run (examples/simple-research-kernel, exported 2026-07-02 from
 * .agent-kernel/trace.db into __fixtures__/research-run.json).
 *
 * The fixture exercises: phase_start + container_start seed events with no
 * piSessionId/runId (app-level orphans), spawned sub-agents linked by
 * parentSessionId + parentToolUseId, provisioning (system prompt + context
 * build + resolved inputs), tool call pairing by spanId, single-run pi
 * sessions (run wrapper skipped), pi turn lifecycle points, and unknown
 * pi_agent_* event types hitting the generic fallback.
 *
 * Any snapshot diff means the builder's public output changed — refactors
 * must keep these snapshots byte-identical.
 */
import { describe, expect, it } from "bun:test";

import type { TraceSpan } from "@evilmartians/agent-prism-types";

import { buildTraceSpans } from "../build-trace-spans";
import type {
  AgentRun,
  KernelContainerSummary,
  PiAgentSession,
  TraceEvent,
} from "../types";

import modelNodesDemoFixture from "./__fixtures__/model-nodes-demo.json";
import fixture from "./__fixtures__/research-run.json";
import stateDemoFixture from "./__fixtures__/state-demo-run.json";

const events = fixture.events as TraceEvent[];
const piSessions = fixture.pi_sessions as PiAgentSession[];
const agentRuns = fixture.agent_runs as AgentRun[];
const containers = fixture.containers as KernelContainerSummary[];

/** JSON-safe deep copy of a span tree with Dates rendered as ISO strings. */
function normalize(spans: TraceSpan[]): unknown[] {
  return spans.map((span) => ({
    id: span.id,
    title: span.title,
    type: span.type,
    status: span.status,
    startTime: span.startTime.toISOString(),
    endTime: span.endTime.toISOString(),
    duration: span.duration,
    input: span.input,
    output: span.output,
    attributes: span.attributes,
    raw: span.raw,
    children: span.children ? normalize(span.children) : undefined,
  }));
}

describe("buildTraceSpans characterization (research-run fixture)", () => {
  it("matches the pinned output tree for the live-UI call shape (no containers arg)", () => {
    const spans = buildTraceSpans(events, piSessions, agentRuns);
    expect(normalize(spans)).toMatchSnapshot();
  });

  it("matches the pinned output tree when container summaries are provided", () => {
    const spans = buildTraceSpans(events, piSessions, agentRuns, containers);
    expect(normalize(spans)).toMatchSnapshot();
  });
});

/**
 * Second characterization — the 8-run state-demo session (exported
 * 2026-07-27 from examples/simple-research-kernel/.agent-kernel/trace.db).
 * Unlike research-run.json this trace carries pi_request_snapshot events,
 * so it pins the turn-ownership nesting: every tool call and assistant
 * reply sits under the Turn span that issued it, inside Run #n wrappers
 * (multi-run session). research-run.json above stays byte-identical,
 * proving the no-snapshot flat fallback.
 */
describe("buildTraceSpans characterization (state-demo fixture, turn nesting)", () => {
  it("matches the pinned turn-nested output tree", () => {
    const spans = buildTraceSpans(
      stateDemoFixture.events as TraceEvent[],
      stateDemoFixture.pi_sessions as PiAgentSession[],
      stateDemoFixture.agent_runs as AgentRun[],
    );
    expect(normalize(spans)).toMatchSnapshot();
  });
});

/**
 * Third characterization — the model-nodes demo, generated by
 * examples/simple-research-kernel/scripts/model-nodes-demo/generate-fixture.ts
 * (regenerate there; never edit the JSON by hand). One GameCube worker job
 * with every model-node shape: call and decision node rows under the worker
 * run they describe, a gate holding step checks and decisions, a codemode
 * tool with nested calls three levels deep, an abstained decision, a failed
 * call, and retry sessions (attempt rows under a summary row, and one session
 * whose attempts sit under two different parent runs).
 */
describe("buildTraceSpans characterization (model-nodes-demo fixture)", () => {
  const demoEvents = modelNodesDemoFixture.events as TraceEvent[];
  const demoPiSessions = modelNodesDemoFixture.pi_sessions as PiAgentSession[];
  const demoAgentRuns = modelNodesDemoFixture.agent_runs as AgentRun[];
  const demoContainers = modelNodesDemoFixture.containers as KernelContainerSummary[];

  it("matches the pinned output tree for the live-UI call shape (no containers arg)", () => {
    const spans = buildTraceSpans(demoEvents, demoPiSessions, demoAgentRuns);
    expect(normalize(spans)).toMatchSnapshot();
  });

  it("matches the pinned output tree when container summaries are provided", () => {
    const spans = buildTraceSpans(demoEvents, demoPiSessions, demoAgentRuns, demoContainers);
    expect(normalize(spans)).toMatchSnapshot();
  });

  /**
   * The DS viewer-ui routes click and wait on `[data-span-id="<target>"]`, and
   * registry-prove requires each selector to match exactly one element. So
   * every route target must be one span of the kind its route expects, and
   * the two "click, then wait for a child" routes need that child under it.
   */
  it("route targets are unique in the demo fixture", () => {
    const spans = buildTraceSpans(demoEvents, demoPiSessions, demoAgentRuns, demoContainers);
    const found = new Map<string, Array<{ eventType: string | undefined; parentId: string | null }>>();
    const visit = (list: TraceSpan[], parentId: string | null) => {
      for (const span of list) {
        const eventType = span.attributes?.find((attr) => attr.key === "event_type")?.value.stringValue;
        found.set(span.id, [...(found.get(span.id) ?? []), { eventType, parentId }]);
        visit(span.children ?? [], span.id);
      }
    };
    visit(spans, null);

    const targets = modelNodesDemoFixture.fixture.routeTargets;
    const expectedKinds: Record<keyof typeof targets, string> = {
      R2: "call_container",
      R3: "decision_container",
      R4: "decision_container",
      ABSTAIN: "decision_container",
      FAILED_CALL: "call_container",
      GATE_SPAN: "gate_start",
      CODEMODE_SPAN: "tool_call_start",
      NESTED_READ_SPAN: "tool_call_start",
      RETRY_DECISION: "decision_container",
      RETRY_ATTEMPT_2: "decision_attempt",
    };
    for (const [key, spanId] of Object.entries(targets) as Array<[keyof typeof targets, string]>) {
      const matches = found.get(spanId) ?? [];
      expect({ key, kinds: matches.map((match) => match.eventType) }).toEqual({ key, kinds: [expectedKinds[key]] });
    }
    expect(found.get(targets.NESTED_READ_SPAN)?.[0]?.parentId).toBe(targets.CODEMODE_SPAN);
    expect(found.get(targets.RETRY_ATTEMPT_2)?.[0]?.parentId).toBe(targets.RETRY_DECISION);
  });
});
